//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Assigner : MonoBehaviour
{
	void Start() {
		/*var coms = this.gameObject.GetComponents<NewBehaviourScript>();
		var mgr = GroupManager.main;
		coms[0].name = "I are zero";
		coms[1].name = "I are ones";
		mgr.group["Normal"].Add(coms[0]);
		mgr.group["Abnormal"].Add(coms[1]);
		mgr.group["Weird"].Add(coms[0]);
		mgr.group["Weird"].Add(coms[1]);*/
	}

	void Update() {
		var mgr = GroupManager.main;
		if (Input.GetKeyDown(KeyCode.Q)) {
			mgr.activeGroup = mgr.group["Normal"];
		}
		if (Input.GetKeyDown(KeyCode.W)) {
			mgr.activeGroup = mgr.group["Abnormal"];
		}
		if (Input.GetKeyDown(KeyCode.E)) {
			mgr.activeGroup = mgr.group["Weird"];
		}
	}
}

